"""create the Table 'advertiement'

Revision ID: 148936170d27
Revises: 
Create Date: 2021-08-05 20:13:39.741649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148936170d27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logtype', sa.Integer(), nullable=True),
    sa.Column('wp_type', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('banner_id', sa.Integer(), nullable=True),
    sa.Column('werbeplatz_id', sa.Integer(), nullable=True),
    sa.Column('peer_ip', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('proxy_ip', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('network', sa.Integer(), nullable=True),
    sa.Column('browser', sa.Integer(), nullable=True),
    sa.Column('os', sa.Integer(), nullable=True),
    sa.Column('screen_res', sa.Integer(), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('delivered_as', sa.Integer(), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('connection', sa.Integer(), nullable=True),
    sa.Column('fvers', sa.Integer(), nullable=True),
    sa.Column('gk', sa.Integer(), nullable=True),
    sa.Column('mdev', sa.Integer(), nullable=True),
    sa.Column('subreq', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('svz_id', sa.String(length=20), nullable=True),
    sa.Column('fraud_action', sa.Integer(), nullable=True),
    sa.Column('fraud_detection_results', sa.Integer(), nullable=True),
    sa.Column('used_batch_media', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement')
    # ### end Alembic commands ###
